### ISSUE TITLE
Possible optimization for getSegDistSq

### ISSUE THREAD

**Issue by hollasch** [mapbox/polylabel#77] opened 2020-12-10 03:30 UTC
I believe there are some promising optimizations of the `getSegDistSq()` function. In the examples below, let's consider the current polylabel `getSegDistSq()` function as solution A.

Solution B
-----------
Instead of storing a polygon as an array of vertices, you can store it as an array of segments, where each segment has the following data:

    struct PolygonSegment {
        Point2D  Q;
        Vector2D D;
        double   invNormDSquared; // = 1/dot(D,D)
    }

    double getSegDistSq(const Point2D& P, const PolygonSegment& segment) {
        Vector2D V = P - segment.Q;
        double t = dot(V,segment.D) * segment.invNormDSquared;

        if (t >= 1)
            V -= segment.D;
        else if (t > 0)
            V -= t*segment.D;

        return dot(V,V);
    }

Alternatively without the geometry types:

    struct PolygonSegment {
        double Qx, Qy;
        double Dx, Dy;
        double invNormDSquared;
    }

    double getSegDistSq(double Px, double Py, const PolygonSegment& segment) {
        auto Vx = Px - segment.Qx;
        auto Vy = Py - segment.Qy;
        auto t = ((Vx * segment.Dx) + (Vy * segment.Dy)) * segment.invNormDSquared;

        if (t >= 1) {
            Vx -= segment.Dx;
            Vy -= segment.Dy;
        } else if (t > 0) {
            Vx -= t * segment.Dx;
            Vy -= t * segment.Dy;
        }

        return Vx*Vx + Vy*Vy;
    }

(I can show the derivation better if you're interested.)

This saves up to 5 additions, 1 multiply and 1 division over the original solution (solution A).

Solution C
-----------
Note that you can shave off one additional multiply for all cases by increasing segment data by two doubles each:

    struct PolygonSegment {
        double Qx, Qy; // Starting point of segment
        double Ex, Ey; // End point of segment
        double Ux, Uy; // Unit vector along segment direction
        double length; // Segment length
    }

    double getSegDistSq(double Px, double Py, const PolygonSegment& segment) {
        auto Vx = Px - segment.Qx;
        auto Vy = Py - segment.Qy;
        auto t = (Vx * segment.Ux) + (Vy * segment.Uy);

        if (t > segment.length) {
            Vx = Px - segment.Ex;
            Vy = Px - segment.Ey;
        } else if (t > 0) {
            Vx -= t * segment.Ux;
            Vy -= t * segment.Uy;
        }

        return Vx*Vx + Vy*Vy;
    }

This saves an additional multiply compared to solution B.

Solution D
-----------
But wait! We're trying to find the shortest distance between the point and the polygon. So I can ignore all segments that can't yield a closer intersection than the one I already have. We can achieve this by considering a circle that encloses the line segment, to determine us the closest possible distance between the point and the segment, like so:

    struct PolygonSegment {
        double Qx, Qy; // Starting point of segment
        double Ex, Ey; // End point of segment
        double Ux, Uy; // Unit vector along segment direction
        double length; // Segment length
    }

    double getSegDistSq(double Px, double Py, const PolygonSegment& segment, double& closestSoFarSquared) {
        auto Vx = Px - segment.Qx;
        auto Vy = Py - segment.Qy;

        double minDistSquared = Vx*Vx + Vy*Vy - segment.lengthSquared;
        if (minDistSquared > closesSoFarSquared)
            return;

        auto t = (Vx * segment.Ux) + (Vy * segment.Uy);

        if (t > segment.length) {
            Vx = Px - segment.Ex;
            Vy = Px - segment.Ey;
        } else if (t > 0) {
            Vx -= t * segment.Ux;
            Vy -= t * segment.Uy;
        }

        auto dSquared = Vx*Vx + Vy*Vy;
        if (dSquared < closesSoFarSquared)
            closesSoFarSquared = dSquared;

        return dSquared;
    }

This leaves us with a tiny savings over solution A in the near case (1 division, 1 or 0 additions). However, the common case of being too far to hope for a closer solution leaves us with a significant savings: 5 additions instead of 11, 2 multiplies instead of 6, and no divisions compared to the orginal 1. For complex polygons, there's definite promise, and for simple polygons, we're still a bit ahead -- the worst we did was trade an addition for a division. Still pretty good!

Results
--------
Here's the final tally of operations for each approach:

    | Version | Condition | Adds | Mults | Divs |
    |---------+-----------+------+-------+------|
    |   A     |   t < 0   |  11  |   6   |  1   |
    |   B     |   t < 0   |   6  |   5   |  0   |
    |   C     |   t < 0   |   6  |   4   |  0   |
    |   D     |   t < 0   |  10  |   6   |  0   |
    |---------+-----------+------+-------+------|
    |   A     | 0 < t < 1 |  13  |   8   |  1   |
    |   B     | 0 < t < 1 |   8  |   7   |  0   |
    |   C     | 0 < t < 1 |   8  |   6   |  0   |
    |   D     | 0 < t < 1 |  12  |   8   |  0   |
    |---------+-----------+------+-------+------|
    |   A     |   1 < t   |  10  |   6   |  1   |
    |   B     |   1 < t   |   7  |   5   |  0   |
    |   C     |   1 < t   |   7  |   4   |  0   |
    |   D     |   1 < t   |  11  |   6   |  0   |
    |---------+-----------+------+-------+------|
    |   D     |    Far    |   5  |   2   |  0   |
    +---------+-----------+------+-------+------+

Note that I haven't tested this, either for correctness or for performance. If anyone has the requisite setup to try this out in the project code, I'm hopeful that the results would be good.

**Comment by hollasch** [comment] 2020-12-10 05:33
On reflection, I'm feeling shaky about solution D, specifically the `minDistSquared` value. I need a point that is cheap to compute that is guaranteed to be nearer P than any point on the line segment.

**Comment by mourner** [comment] 2020-12-10 11:44
@hollasch thanks for the issue! It's definitely worth exploring any possible optimizations, but note that we also want to avoid memory footprint regressions (storing segments instead of points would need a lot more allocations), and we also prefer code simplicity and maintainability over micro-optimizations if they don't bring a substantial improvement. 

Option D is an interesting idea, but in its current form will fail if a point is very close to the segment but far from its endpoints, as you noticed in the follow-up comment.

**Comment by hollasch** [comment] 2020-12-10 17:49
Understood about memory; you may be operating under different constraints. Regarding your second point, this isn't really a failure, as this is a trivial rejection test. The benefit of such testing is that it frequently and quickly skips a lot of computation. Situations that fail the trivial rejection but which eventually get rejected after the full rejection are just part of the game. The idea is that many or most points are rejected quickly, ultimately yielding (possibly significant) speedup. Often a sloppier trivial rejection test outperforms a more accurate one.

**Comment by hollasch** [comment] 2020-12-10 17:52
To be clear, my comment about `minDistSquared` is that I'm not certain it's sound to add the two distances squared. Trying to get my head around whether it's sloppy enough.

**Comment by hollasch** [comment] 2020-12-10 17:57
Oh, another thought about the memory footprint — this computation only happens once per polygon, so can be freed after it's done. Still possibly an issue when working with a garbage-collected language like JavaScript, but should be fine with C++. If you use the start point of the next segment as your endpoint, you end up inflating polygon memory by 2.5x, which in most cases should be fine.

**Comment by mourner** [comment] 2020-12-10 17:58
@hollasch oh, I guess I misunderstood what your trivial rejection actually checks. It's certainly intriguing — need to check whether such a criteria is exhaustive (e.g. there are no edge cases that get rejected when they may end up as a better solution), and try benchmarking!

**Comment by mourner** [comment] 2024-06-26 17:59
> storing segments instead of points would need a lot more allocations

Will close the issue because of the point above but feel free to open a new one if there's a potential optimization without changing the storage format.

**Closed by mourner** 2024-06-26 17:59 UTC
Labels: question
