### ISSUE TITLE
Label positioning is wrong on rooms that aren't perfectly square?

### ISSUE THREAD

**Issue by iomturner** [mapbox/polylabel#58] opened 2020-03-24 18:26 UTC
@mourner if you remember I previously posted having issues with L shaped rooms (https://github.com/mapbox/polylabel/issues/55) where you told me to decrease the tolerance to `0.00001 `. But now I noticed another issue with rooms that aren't perfectly square:

https://stackblitz.com/edit/mapbox-simple-map-cbnty5?file=index.ts

<img width="255" alt="Screen Shot 2020-03-24 at 1 27 42 PM" src="https://user-images.githubusercontent.com/52937057/77463208-4288a580-6dd3-11ea-81f5-961bfdcc9186.png">

not sure if this helps but i also posted this when i zoomed into the points:

<img width="561" alt="Screen Shot 2020-03-24 at 1 39 38 PM" src="https://user-images.githubusercontent.com/52937057/77464310-fa6a8280-6dd4-11ea-8a17-7ac6ddf3d85d.png">

**Comment by iomturner** [comment] 2020-03-25 19:12
i have noticed out of the two rooms/ squares. the one of the right is not 100% square which with the added tolerance level so low it off centers the label... but for the other one on the left...

**Comment by mourner** [comment] 2020-03-25 23:13
Duplicate of #33

**Closed by mourner** 2020-03-25 23:13 UTC
